import { describe, expect, test } from "bun:test"
import { checkpointHasRealContent } from "../../src/session/checkpoint"
import { CHECKPOINT_TEMPLATE } from "../../src/session/checkpoint-templates"

describe("checkpointHasRealContent (version-agnostic template detection)", () => {
  test("empty / whitespace → false", () => {
    expect(checkpointHasRealContent("")).toBe(false)
    expect(checkpointHasRealContent("   \n\n  ")).toBe(false)
  })

  test("the pristine template → false (no distilled content yet)", () => {
    expect(checkpointHasRealContent(CHECKPOINT_TEMPLATE)).toBe(false)
  })

  test("a REFORMATTED template still → false (robust to template edits)", () => {
    // Simulate the template constant being reformatted: different header
    // wording, extra blank lines, placeholder casing. A byte-equality check
    // against CHECKPOINT_TEMPLATE would misclassify this as real content; the
    // structural check must still see it as empty.
    const reformatted = [
      "# Session checkpoint  ",
      "",
      "",
      "## §1  Active Intent",
      "_some rewritten italic instruction line here._",
      "(None Yet)",
      "",
      "## §2 — Next Action",
      "_instruction_",
      "( none )",
    ].join("\n")
    expect(checkpointHasRealContent(reformatted)).toBe(false)
  })

  test("a filled-in section → true", () => {
    const filled = CHECKPOINT_TEMPLATE.replace("(none yet)", "> \"implement the /rebuild command\"")
    expect(checkpointHasRealContent(filled)).toBe(true)
  })

  test("real content mixed with placeholders → true", () => {
    const mixed = [
      "# Session checkpoint",
      "## §1 Active intent",
      "The user is debugging a checkpoint wedge.",
      "## §2 Next concrete action",
      "(none yet)",
    ].join("\n")
    expect(checkpointHasRealContent(mixed)).toBe(true)
  })

  test("headers + italics + placeholders only → false", () => {
    const emptyish = [
      "# Session checkpoint",
      "_Generated by checkpoint writer._",
      "## §1 Active intent",
      "_User's most recent request._",
      "(none yet)",
      "## §3 Directives",
      "(none)",
    ].join("\n")
    expect(checkpointHasRealContent(emptyish)).toBe(false)
  })
})
